# Social Vulnerability Project
## Data Preparation Module

In [1]:
# imports

# general imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# my imports
import acquire

In [2]:
county_df = acquire.county_data()

In [3]:
census_df = acquire.census_data()

In [4]:
census_df.head()

,county,fips,population,pop_error,socioeconomic,composition,minority,housing,svi_ranking,turnout,registered
0,ANDERSON,48001950100,5164,525,0.3853,0.7610,0.1308,0.7545,0.4965,4718.0,27788.0
1,ANDERSON,48001950401,4872,263,0.4162,0.0230,0.3439,0.5421,0.2477,4718.0,27788.0
2,ANDERSON,48001950402,7548,356,0.6895,0.0626,0.3219,0.3123,0.3422,4718.0,27788.0
3,ANDERSON,48001950500,4569,520,0.7202,0.7878,0.6467,0.9167,0.8433,4718.0,27788.0
4,ANDERSON,48001950600,5570,754,0.5552,0.4861,0.2766,0.7387,0.5470,4718.0,27788.0

In [5]:
census_df['pop_error_percent'] = (census_df['pop_error'] / census_df['population']).round(4)

In [10]:
census_df['pop_error_percent'] = census_df['pop_error_percent'].replace(np.inf, 0.000)

In [11]:
census_df['pop_error_percent'].value_counts()

0.0000    47
0.1134    15
0.0933    14
0.0911    14
0.0961    13
          ..
0.1748     1
0.0574     1
0.2421     1
0.0483     1
0.5141     1
Name: pop_error_percent, Length: 1319, dtype: int64

In [12]:
census_df['pop_error_percent'].nlargest()

2538    2.0000
260     1.7500
5008    1.6286
1198    1.4000
2191    1.0833
Name: pop_error_percent, dtype: float64

#### Population Error Takeaways:
- All are small enough (<=2%) so we can feel good about using the entire data set
- Going to drop the 'pop_error_percent' column, now that we know data integrity is strong

In [14]:
# now let's make a column to look at turnout percent based on total population
census_df['turnout_percent_ct'] = census_df['turnout'] / census_df['population']

In [22]:
census_df['population'].nsmallest(keep='all')

107     0
108     0
261     0
263     0
264     0
560     0
606     0
700     0
720     0
779     0
1199    0
1796    0
3148    0
3569    0
3719    0
3743    0
4045    0
4204    0
4367    0
4626    0
4667    0
4704    0
4931    0
4956    0
Name: population, dtype: int64

In [24]:
fraud = census_df[census_df['turnout'] > census_df['population']]

In [25]:
fraud

,county,fips,population,pop_error,socioeconomic,composition,minority,housing,svi_ranking,turnout,registered,pop_error_percent,turnout_percent_ct
3,ANDERSON,48001950500,4569,520,0.7202,0.7878,0.6467,0.9167,0.8433,4718.0,27788.0,0.1138,1.032611
5,ANDERSON,48001950700,2479,352,0.6887,0.9278,0.7091,0.9378,0.9050,4718.0,27788.0,0.1420,1.903187
8,ANDERSON,48001950902,4513,767,0.4302,0.5947,0.2072,0.7032,0.4781,4718.0,27788.0,0.1700,1.045424
10,ANDERSON,48001951100,4155,556,0.3527,0.3352,0.2401,0.4943,0.3358,4718.0,27788.0,0.1338,1.135499
16,ANGELINA,48005001300,5052,615,0.7901,0.8133,0.0021,0.1617,0.4401,5963.0,50779.0,0.1217,1.180325
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5213,WILSON,48493000201,2486,299,0.7027,0.4949,0.5346,0.4360,0.5776,4136.0,31428.0,0.1203,1.663717
5215,WILSON,48493000102,3858,409,0.4938,0.6949,0.2473,0.3213,0.4197,4136.0,31428.0,0.1060,1.072058
5224,WISE,48497150403,4205,428,0.5112,0.5765,0.2200,0.1657,0.3306,4969.0,39850.0,0.1018,1.181688
5225,WISE,48497150300,2650,327,0.2656,0.2710,0.0499,0.1936,0.1544,4969.0,39850.0,0.1234,1.875094
5229,WISE,48497150101,3838,405,0.2414,0.2727,0.0356,0.1182,0.1139,4969.0,39850.0,0.1055,1.294685